name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script:
          cd django
          git pull
          docker build --tag "docker.server" .
          docker compose up -d
        
