name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    

    - name: SSH into VPS and run commands
      run: |
        ssh {{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
        cd django
        git pull
        docker build --tag "docker.server" .
        docker-compose up -d
        EOF
      env:
        SSHKEY: ${{ secrets.SSHKEY }}
        HOST: ${{ secrets.HOST }}
        PORT: ${{ secrets.PORT }}
        USERNAME: ${{ secrets.USERNAME }}